Iss198 weighted eastasia
openghg/openghg_inversions pull request #199
Opened 2024-08-30 10:04 UTC by qq23840

Update the basis module such that the 'weighted' algorithm can be used for the EASTASIA domain. This incorporates a land-sea split netCDF file. 

* **Please check if the PR fulfills these requirements**

- [x] Closes #198 
- [x] Tests added and passing (no new tests, but tests updated to reflect change in code)
- [x] Documentation and tutorials updated/added
- [x] Added an entry to the `CHANGELOG.md` file
- [x] Added any new requirements to `requirements.txt`

2024-08-30 10:38 UTC, hdelongueville commented on openghg_inversions/basis/algorithms/_weighted.py
Wouldn't it be useful to add a warning message if there is no country-landsea file linked to the domain (i.e., domain other than EASTASIA and EUROPE)? 
e.g.
if domain == 'EASTASIA':
        landsea_indices = xr.open_dataset(Path(__file__).parent / "country-land-sea_EASTASIA.nc")
elif domain == 'EUROPE':
        landsea_indices = xr.open_dataset(Path(__file__).parent / "country-EUROPE-UKMO-landsea-2023.nc")
else:
        ++ add a warning message here like "No landsea mask file related to {domain}. The file country-EUROPE-UKMO-landsea-2023.nc is used instead." ++
        landsea_indices = xr.open_dataset(Path(__file__).parent / "country-EUROPE-UKMO-landsea-2023.nc")

2024-08-30 11:01 UTC, qq23840 commented on openghg_inversions/basis/algorithms/_weighted.py
Yes sounds sensible - I'll add it with a logger warning

2024-08-30 11:22 UTC, hdelongueville approved these changes
Looks good to me!

2024-09-02 08:47 UTC, brendan-m-murphy requested changes
Around line 370 of `basis/_functions.py`, you need to pass "domain" to the inner region basis function.

I guess we should have a test for the fixed out regions basis function, if we don't already. (I think this should be an easy modification of the existing basis functions tests, but if it isn't, I can try to make a new test.)

2024-09-02 09:38 UTC, brendan-m-murphy approved these changes
Look good, thanks!

2024-09-02 09:45 UTC, merged